"""followers

Revision ID: 76efa8989bdb
Revises: 5cb9121e4b40
Create Date: 2024-04-02 13:33:39.735106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76efa8989bdb'
down_revision = '5cb9121e4b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
